#!/bin/sh
if [ "$2" = DEINSTALL ]; then
	echo "-------------------------------------------------------------------------"
	echo "If you are permanently removing this port,"
	echo "you should manually remove the irccat user and group."
	echo "-------------------------------------------------------------------------"
fi
