# $FreeBSD$

PORTNAME=	tclsoap
PORTVERSION=	1.6.7
CATEGORIES=	net
MASTER_SITES=	SF/${PORTNAME}/${PORTNAME}/TclSOAP-${PORTVERSION}
DISTNAME=	TclSOAP-${PORTVERSION}

MAINTAINER=	dereckson@gmail.com
COMMENT=	SOAP and XML-RPC support for TCL library

WRKSRC=		${WRKDIR}/${PORTNAME}${PORTVERSION}

USE_AUTOTOOLS=	autoconf:autoconf

#tclsoap/tclsoap/TclSOAP-1.6.7/TclSOAP-1.6.7.tar.gz

.include <bsd.port.mk>
