# Created by: Dereckson <dereckson@gmail.com>
# $FreeBSD$

PORTNAME=	dibbler
PORTVERSION=	1.0.0.r1
CATEGORIES=	net
MASTER_SITES=	SF/${PORTNAME}/${PORTNAME}/${PORTVERSION:S/.r/RC/}/ http://klub.com.pl/dhcpv6/dibbler/
DISTNAME=	${PORTNAME}-${PORTVERSION:S/.r/RC/}

MAINTAINER=	dereckson@gmail.com
COMMENT=	DHCPv6 stateless and stateful client

LICENSE=	GPLv2

USE_AUTOTOOLS=	aclocal
USE_GCC=	4.6+

.include <bsd.port.mk>
